backend = "glx";
vsync = true;

blur-method = "none";
blur-strength = 0;

corner-radius = 6;

dim-background = false;
dim-value = 0.0;

use-damage = true;
unredir-if-possible = true;

rounded-corners-exclude = [
  "window_type = 'dock'"
];
