#!/usr/bin/env bash
set -euo pipefail

choice="${1:-Arch}"
cfg="${EWW_CONFIG_DIR:-$HOME/.config/eww}"
state_dir="$cfg/state"
state_file="$state_dir/sidebar-logo"

mkdir -p "$state_dir"

case "$choice" in
  Arch) logo="" ;;
  SuperMachine) logo="󰣇" ;;
  Linux) logo="" ;;
  Terminal) logo="" ;;
  Code) logo="󰨞" ;;
  Star) logo="" ;;
  Lightning) logo="" ;;
  Fire) logo="" ;;
  Rocket) logo="" ;;
  Gear) logo="󰒓" ;;
  Diamond) logo="◆" ;;
  Cross) logo="✚" ;;
  Heart) logo="" ;;
  Shield) logo="󰞀" ;;
  Crown) logo="󰯆" ;;
  Cube) logo="" ;;
  Circle) logo="●" ;;
  Triangle) logo="▲" ;;
  Hex) logo="⬢" ;;
  Wave) logo="≋" ;;
  Eye) logo="" ;;
  Compass) logo="" ;;
  Atom) logo="" ;;
  Chip) logo="" ;;
  Keyboard) logo="" ;;
  Monitor) logo="󰍹" ;;
  Gamepad) logo="" ;;
  Headphones) logo="" ;;
  Music) logo="" ;;
  Coffee) logo="" ;;
  Mug) logo="☕" ;;
  Tea) logo="◔" ;;
  Cocoa) logo="♨" ;;
  Lightbulb) logo="" ;;
  Bookmark) logo="" ;;
  Pen) logo="" ;;
  Magic) logo="" ;;
  Sliders) logo="" ;;
  Moon) logo="" ;;
  Sun) logo="" ;;
  Cloud) logo="" ;;
  Sparkle) logo="✦" ;;
  BoltCircle) logo="󱐋" ;;
  FlameAlt) logo="󰈸" ;;
  Skull) logo="󰚌" ;;
  Ghost) logo="󰊠" ;;
  Circuit) logo="󰘚" ;;
  Planet) logo="󰯉" ;;
  Anchor) logo="" ;;
  Leaf) logo="" ;;
  Snow) logo="" ;;
  Radioactive) logo="☢" ;;
  Biohazard) logo="☣" ;;
  Smile) logo="" ;;
  Target) logo="󰀘" ;;
  Key) logo="" ;;
  Lock) logo="" ;;
  Unlock) logo="" ;;
  Home) logo="" ;;
  Folder) logo="" ;;
  Download) logo="" ;;
  Upload) logo="" ;;
  Wifi) logo="" ;;
  Bluetooth) logo="" ;;
  Battery) logo="" ;;
  Power) logo="" ;;
  Plug) logo="" ;;
  Bell) logo="" ;;
  Book) logo="" ;;
  Bible) logo="✝" ;;
  Flame) logo="♨" ;;
  Flower) logo="✿" ;;
  Peace) logo="☮" ;;
  YinYang) logo="☯" ;;
  Aries) logo="♈" ;;
  Gemini) logo="♊" ;;
  Leo) logo="♌" ;;
  Scorpio) logo="♏" ;;
  Aquarius) logo="♒" ;;
  Pisces) logo="♓" ;;
  Chess) logo="♞" ;;
  Club) logo="♣" ;;
  Spade) logo="♠" ;;
  HeartSuit) logo="♥" ;;
  MusicAlt) logo="♫" ;;
  Infinity) logo="∞" ;;
  Section) logo="§" ;;
  Check) logo="✓" ;;
  XMark) logo="✕" ;;
  Plus) logo="✚" ;;
  FourPoint) logo="✥" ;;
  FlowerStar) logo="✾" ;;
  CircleStar) logo="✪" ;;
  EightStar) logo="✸" ;;
  SunAlt) logo="☀" ;;
  CloudAlt) logo="☁" ;;
  Umbrella) logo="☂" ;;
  Snowman) logo="☃" ;;
  Comet) logo="☄" ;;
  Phone) logo="" ;;
  Camera) logo="" ;;
  Paint) logo="" ;;
  Flask) logo="" ;;
  Wrench) logo="" ;;
  Bug) logo="" ;;
  Database) logo="" ;;
  Server) logo="" ;;
  Git) logo="" ;;
  Github) logo="" ;;
  Branch) logo="" ;;
  Desktop) logo="" ;;
  Grid) logo="▦" ;;
  Panel) logo="▌" ;;
  Stack) logo="▤" ;;
  Prompt) logo="❯" ;;
  Globe) logo="" ;;
  Map) logo="" ;;
  Flag) logo="" ;;
  Trophy) logo="" ;;
  Gift) logo="" ;;
  Magnet) logo="" ;;
  Puzzle) logo="" ;;
  Train) logo="" ;;
  Car) logo="" ;;
  Plane) logo="" ;;
  Ship) logo="" ;;
  Hourglass) logo="" ;;
  Calendar) logo="" ;;
  Clock) logo="" ;;
  Signal) logo="" ;;
  Bars) logo="" ;;
  Layers) logo="" ;;
  TerminalAlt) logo="" ;;
  Package) logo="󰏗" ;;
  ArchAlt) logo="󰣇" ;;
  WaveBox) logo="▰" ;;
  HollowStar) logo="☆" ;;
  FilledSquare) logo="■" ;;
  HollowSquare) logo="□" ;;
  FilledCircle) logo="●" ;;
  HollowCircle) logo="○" ;;
  DoubleDiamond) logo="❖" ;;
  NorthStar) logo="✧" ;;
  EightSpoke) logo="✺" ;;
  BlackSun) logo="☀" ;;
  Crescent) logo="☾" ;;
  CrossAlt) logo="☩" ;;
  Maltese) logo="✠" ;;
  DiceOne) logo="⚀" ;;
  DiceTwo) logo="⚁" ;;
  DiceThree) logo="⚂" ;;
  DiceFour) logo="⚃" ;;
  DiceFive) logo="⚄" ;;
  DiceSix) logo="⚅" ;;
  Warning) logo="⚠" ;;
  GearAlt) logo="⚙" ;;
  AnchorAlt) logo="⚓" ;;
  Swords) logo="⚔" ;;
  Scales) logo="⚖" ;;
  FlowerAlt) logo="⚘" ;;
  AtomAlt) logo="⚛" ;;
  Fleur) logo="⚜" ;;
  Soccer) logo="⚽" ;;
  Baseball) logo="⚾" ;;
  Thunder) logo="ϟ" ;;
  Lambda) logo="λ" ;;
  Sigma) logo="Σ" ;;
  Omega) logo="Ω" ;;
  Custom)
    logo="${2:-}"
    ;;
  *)
    logo="$choice"
    ;;
esac

[ -n "$logo" ] || exit 0

printf '%s\n' "$logo" > "$state_file"
eww -c "$cfg" update SIDEBAR_LOGO="$logo" >/dev/null 2>&1 || true
